# For more information: https://laravel.com/docs/sail
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sparks-cannabis-app:latest
    environment:
      # Set all necessary env vars here or in Coolify dashboard
      APP_ENV: production
      APP_DEBUG: 'false'
      # DB_HOST, DB_DATABASE, DB_USERNAME, DB_PASSWORD, etc. should be set in Coolify
    ports:
      - '80:80'
    volumes:
      - storage-data:/var/www/html/storage
      - public-data:/var/www/html/public
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - sail
    restart: unless-stopped
networks:
  sail:
    driver: bridge
volumes:
  storage-data:
  public-data:
