version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sparkscannabis-app:latest
    container_name: sparkscannabis-app
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL:-http://localhost}
      
      # Database
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-sparks_cannabis}
      DB_USERNAME: ${DB_USERNAME:-sparks}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      
      # Redis
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD:-null}
      REDIS_PORT: 6379
      
      # Cache & Session
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis
      
      # Mail
      MAIL_MAILER: ${MAIL_MAILER:-smtp}
      MAIL_HOST: ${MAIL_HOST:-localhost}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-tls}
    ports:
      - "8080:80"
    volumes:
      - app-storage:/var/www/html/storage
      - app-uploads:/var/www/html/public/uploads
    networks:
      - sparkscannabis-network

  # MySQL Database
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: sparkscannabis-mysql:latest
    container_name: sparkscannabis-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-sparks_cannabis}
      MYSQL_USER: ${DB_USERNAME:-sparks}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - sparkscannabis-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  # Redis Cache
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    image: sparkscannabis-redis:latest
    container_name: sparkscannabis-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - sparkscannabis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # SFTP Server
  sftp:
    build:
      context: .
      dockerfile: Dockerfile.sftp
    image: sparkscannabis-sftp:latest
    container_name: sparkscannabis-sftp
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      - sftp-data:/home/sftpuser
      - app-uploads:/home/sftpuser/uploads
    networks:
      - sparkscannabis-network

  # phpMyAdmin (Optional)
  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile.phpmyadmin
    image: sparkscannabis-phpmyadmin:latest
    container_name: sparkscannabis-phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
    ports:
      - "8081:80"
    networks:
      - sparkscannabis-network

networks:
  sparkscannabis-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  sftp-data:
    driver: local
  app-storage:
    driver: local
  app-uploads:
    driver: local